# # ---------- Base ----------
# FROM node:20-bullseye AS base
# WORKDIR /app

# COPY package.json package-lock.json ./
# RUN npm ci

# # ---------- Dev ----------
# FROM base AS dev
# WORKDIR /app

# COPY . .

# # Copy config để PostCSS hoạt động
# COPY postcss.config.js ./postcss.config.js
# COPY tailwind.config.ts ./tailwind.config.ts
# COPY styles ./styles

# ENV NODE_ENV=development
# ENV NEXT_WEBPACK_USE_TURBOPACK=0

# # Ép build Tailwind để sinh CSS trong .next/static/css
# RUN npm run build || true

# EXPOSE 3000
# CMD ["npm", "run", "dev"]

FROM public.ecr.aws/docker/library/node:20-bullseye-slim AS base
#------------------------------------------------
FROM base AS deps
WORKDIR /app

RUN apt-get update && apt-get install -y libc6

RUN npm install -g npm@11.3.0

#package.json and yarn.lock need to be synchronized.
COPY package.json ./
RUN npm install
#------------------------------------------------
FROM base AS builder

WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN npm run build
#------------------------------------------------
FROM base AS runner

WORKDIR /app

COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/public ./public

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"
CMD ["node", "server.js"]